### ISSUE TITLE
Add support for building kernel with os-builder

### ISSUE THREAD

**Issue by amshinde** [kata-containers/osbuilder#116]
We should consider adding support for building kernel with os-builder similar to what we had with Clear Containers. This would simplify the process of generating and testing out a custom kernel.

**Comment by jodh-intel** [comment]
This is a duplicate of #6.

**Comment by jcvenegas** [comment]
@amshinde  @jodh-intel  @Pennyzct  because the config and patches lives in packaging. I wonder what is the best place to add this.

could be here:
`make kernel` that will download runtime repositoy an check what is the latest kernel suggested by versions.yaml then download packaging and apply the patches and config then build the kernel.

in packaging/kernel;
We only need to verify in runtime versions.yaml  and not need to depend in an extra repository.

It is ok if I push this changes  into packaging ?

**Comment by jodh-intel** [comment]
Yes - I think that's what we're going to have to do.

**Comment by jodh-intel** [comment]
Oh - sorry, I see what you mean. I guess it could live in packaging as long as it's simple for the user to only build an (unpackaged) kernel. But wouldn't the advantage of putting it in osbuilder be that the build tooling wouldn't need to be installed on the host? I guess that's only going to be essentially make+gcc but still?

**Comment by amshinde** [comment]
We have added support for this in the packaging repo.
https://github.com/kata-containers/packaging/tree/master/kernel

Closing this.
