### ISSUE TITLE
Cannot setup a debug console for ubuntu rootfs

### ISSUE THREAD

**Issue by amshinde** [kata-containers/osbuilder#258]
Followed all the steps for setting up a debug console for ubuntu-based rootfs here:
https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#set-up-a-debug-console

When I try to socat into the console, it just hangs.

**Comment by grahamwhaley** [comment]
@jodh-intel was working on some stuff around that recently, so maybe has an idea or can ack/nack that it worked for him...

**Comment by jodh-intel** [comment]
Confirmed for ubuntu+debian. I also see journal output being displayed on the hanging connection if I enable agent debug.

Related: #96.

**Comment by jodh-intel** [comment]
Ha - got it! The solution:

```diff
--- kata-debug.service  2019-03-22 13:08:18.295251535 +0000
+++ kata-debug.service.fixed    2019-03-22 13:07:58.102600173 +0000
@@ -8,7 +8,7 @@
 # Must be disabled to allow the job to access the real console
 PrivateDevices=no
 Type=simple
-ExecStart=/usr/bin/bash
+ExecStart=/bin/bash
 Restart=always
```

**Comment by jodh-intel** [comment]
@amshinde - https://github.com/kata-containers/documentation/pull/411.

**Comment by jodh-intel** [comment]
I should probably point out here that it's rather hard to debug a broken debug console since:

- Enabling a debug console requires the proxy debug to be disabled.

  And that turns off the logging of guest kernel boot messages (including those from systemd). So with a debug console enabled, you have no guest debug output!

You *can* switch to vsock mode but that requires building a custom image including the `kata-journald-host-redirect.service` agent service which is fiddly to setup as it requires host-side script support too.

The way I saw the issue was to:
- Set the following in `configuration.toml`:
  ```toml
  kernel_params = "agent.log=debug systemd.log_level=debug systemd.journald.forward_to_syslog=1 systemd.journald.forward_to_console=1"
  ```
- Enable proxy debug (even though "that won't work with a debug console") in `configuration.toml`.
- Create a container.
- Extract the proxy log details from the journal before attempting to connect to the debug console socket.

**Comment by amshinde** [comment]
Fixed with https://github.com/kata-containers/documentation/pull/411
