### ISSUE TITLE
rootfs: Add host based rootfs flavor

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/osbuilder#259]
Add a use case where the rootfs is created from binaries in the host.

This is going to search for binaries in the host
- agent
- iptables 

I will check for the shared libraries that are needed by the binaries and will copy them to the file system. 

Ideally iptables and agent would be static binaries, so rootfs creation would be only copy binaries to the right place.

Benefits: 

Packaging: 
- rootfs can be created at package build time
- initrd could be created a build time
- image may need to be created at post install time but without additional calls to the host package manager (that may be error prompt due to network issues).

Testing/developing: Create an image with additional agent changes only will be needed to put the agent in the host system with new changes. 

Notes:
Systemd based rootfs won't be supported systemd is not easy to copy as just a binary

**Comment by jcvenegas** [comment]
@devimc @sboeuf @egernst  @jodh-intel @bergwolf  @grahamwhaley take a look

**Comment by grahamwhaley** [comment]
That's a pretty wild idea @jcvenegas , but could help cure some of the packaging issues for sure. Be interesting to see what you come up with..

**Comment by jodh-intel** [comment]
This is an interesting idea, but I think there are going to be issues. A few thoughts:

- How can osbuilder be sure that the binaries it's copying are "pristine"? What if the user modified a config file or used `update-alternatives(1)` to modify a provider?
- How can osbuilder deal with a host system which is *in the process of being updated* with `apt`/`dnf` / *etc*? That could result in either a broken rootfs or -- worse -- a rootfs that boots and then fails later due to some file being only partially available or corrupt.
- What about the guest kernel? Is that going to be copied from the host kernel? If so, that may not dtrt and certainly won't be optimised. Also, what about kernel modules if the host kernel uses them (likely)?
- Debugging issues with a rootfs made in this manner is going to be difficult. What will we put into `osbuilder.yaml`? We won't be able to use a debug console either without manually modifying the image and hacking in a static busybox binary for example.
- What if the host build environment is actually a *cross* build environment?

I'm still not clear on the main benefits though - a rootfs could be created at packaging time using osbuilder atm surely? Unless you're talking about running the packaging on particular build systems that don't have network access maybe? If this is the case, that "host" environment may be very restrictive indeed and may not provide the packages required to build the rootfs. Even if it does, there is a change certain configuration files may have been modified to guarantee no network access / limited user access / etc and those config files may not work in the rootfs.

**Comment by jcvenegas** [comment]
> * How can osbuilder be sure that the binaries it's copying are "pristine"? What if the user modified a config file or used `update-alternatives(1)` to modify a provider?
Agree, there is not but way to verify it, but at the same time is a easy way to allow developer to update binaries as needed for testing purposes.

> * How can osbuilder deal with a host system which is _in the process of being updated_ with `apt`/`dnf` / _etc_? That could result in either a broken rootfs or -- worse -- a rootfs that boots and then fails later due to some file being only partially available or corrupt.

I hope this is managed nicely by the package manager doing atomic transactions, not sure how this is handled but is a good question

> * What about the guest kernel? Is that going to be copied from the host kernel? If so, that may not dtrt and certainly won't be optimised. Also, what about kernel modules if the host kernel uses them (likely)?
This is only image rootfs generation about modules, it going to take the same approach as today, copy if a path is provided.


> * Debugging issues with a rootfs made in this manner is going to be difficult. What will we put into `osbuilder.yaml`? We won't be able to use a debug console either without manually modifying the image and hacking in a static busybox binary for example.
I think for osbuilder.yaml the best thing is to add the output of the `binary --version`
For debug console hacking this is going to be easier, just define what things you additionally want to add from your host. 

> * What if the host build environment is actually a _cross_ build environment?
If this is a cross build enviroment I think we can support HOSTDIR enviroment variable to use that directory as host rootfs. 

> I'm still not clear on the main benefits though - a rootfs could be created at packaging time using osbuilder atm surely? Unless you're talking about running the packaging on particular build systems that don't have network access maybe? If this is the case, that "host" environment may be very restrictive indeed and may not provide the packages required to build the rootfs. Even if it does, there is a change certain configuration files may have been modified to guarantee no network access / limited user access / etc and those config files may not work in the rootfs.

You are right, the main issue I'd like to solve here is for systems that is not possible to use a package manager. The packaging scenario is one that fits a lot. Today we add the binary image to the package like a source :( . So for linux distributions adopters the solution is or create the image as part of their releases process (suse has kiwi for this) or create the image at post install that make error prone. 

I am not looking for this as official way to build a rootfs, but if we can work on in and test it for some time and we see it works that may be a good solution for rootfs creation for this use cases.
 
Let me know if this reasons are good to try to implement this does not real value to the project. 

In the case of pacakaging:
```
#Install in build enviroemnt the packages needed
build-requiere: kata-agent, iptables

# 
rootfs_destdir=${DESTDIR}/usr/share/kata/rootfs-dir
./create-rootfs.sh host ${rootfs_destdir}
./create-initrd.sh ${rootfs_destdir}
```

**Comment by marcov** [comment]
I did not notice this before. As you may have seen, I have [opened a PR](https://github.com/kata-containers/osbuilder/issues/311) to integrate dracut in osbuilder, with the goal of providing a distro agnostic way to generate a Kata image / initrd.

**Comment by pmores** [comment]
I'd agree with @marcov's comment above - the dracut-based build method seems to fit the bill quite well WRT this issue and it's reasonably functional by now. If anything's still missing I'd suggest opening a more specific issue and I guess we should consider closing this one in any case.
