### ISSUE TITLE
Build clearlinux rootfs using clearlinux

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/osbuilder#48]
Currently, `rootfs-builder/clearlinux/Dockerfile.in` builds the clearlinux rootfs using fedora 27. We should use clearlinux to build clearlinux.

See: https://github.com/kata-containers/osbuilder/pull/40#discussion_r163490108

**Comment by JerryOpenix** [comment]
Follow below guide to build centos rootfs:
https://github.com/kata-containers/osbuilder/blob/master/rootfs-builder/README.md

I have to set the proxy ip:port explicitly in rootfs.sh instead of only giving it as url.

I use below WAed patch on local server:
diff --git a/rootfs-builder/rootfs.sh b/rootfs-builder/rootfs.sh
index 86b357f..e11d3a8 100755
--- a/rootfs-builder/rootfs.sh
+++ b/rootfs-builder/rootfs.sh
@@ -201,8 +201,8 @@ if [ -n "${USE_DOCKER}" ] ; then
 
        generate_dockerfile "${distro_config_dir}"
        docker build  \
-               --build-arg http_proxy="${http_proxy}" \
-               --build-arg https_proxy="${https_proxy}" \
+               --build-arg http_proxy="http://10.xxx.xxx.xxx:913" \
+               --build-arg https_proxy="https://10.xxx.xxx.xxx:913" \
                -t "${image_name}" "${distro_config_dir}"
 
        # fake mapping if KERNEL_MODULES_DIR is unset
@@ -213,8 +213,8 @@ if [ -n "${USE_DOCKER}" ] ; then
        #https://github.com/clearcontainers/runtime/issues/828
        docker run  \
                --runtime runc  \
-               --env https_proxy="${https_proxy}" \
-               --env http_proxy="${http_proxy}" \
+               --env https_proxy="http://10.xxx.xxx.xxx:913" \
+               --env http_proxy="http://10.xxx.xxx.xxx:913" \
                --env AGENT_VERSION="${AGENT_VERSION}" \
                --env ROOTFS_DIR="/rootfs" \
                --env GO_AGENT_PKG="${GO_AGENT_PKG}" \

**Comment by sohamdigheoss** [comment]
@jodh-intel Can I do this? If yes tag to use will be used in place of @OS_VERSION@? latest or base?

**Comment by jodh-intel** [comment]
Hi @sohamdigheoss - sure, it's all yours! ;) Github won't let me actually assign this issue to you, but this comment is enough for the team to see you're working on this.

I'd use the `latest` version of clearlinux.

**Comment by sohamdigheoss** [comment]
@jodh-intel I have encountered an issue while finding a bundle for gcc in clearlinux.
All of the bundles with gcc(c-basic,rust-basic,etc) have size greater than 2gb which seems a quite excessive to me. 
Then I tried to create my own bundle but it required the mixer bundle which is 3gb in size.
I believe that gcc is required for installing GO so one of the possible solutions is to install and rremoving the bundle after installation is finished but i am not sure if there is further use for gcc and if removing it after use is a viable solution or not.
what do you think should be done here?

**Comment by jodh-intel** [comment]
Thanks for investigating this @sohamdigheoss.

Any thoughts on this @bryteise?

**Comment by jodh-intel** [comment]
Any update on this @sohamdigheoss?

Anyone else able to help out and test this with Clear Linux directly? F27 went EOL in November 2018 so we atleast need to update the `clearlinux/Dockerfile` to specify `fedora:29` (or maybe just `fedora`?) But clearly, the ideal is to not require Fedora for Clear Linux at all ;)

/cc @bryteise.

**Comment by bryteise** [comment]
@jodh-intel I am just now seeing this sorry X(.

@sohamdigheoss I'm not sure on the requirement to have gcc or go in for the rootfs. If it is for building osbuilder then the go-basic bundle I would expect to be sufficient. Could you point me at the set of steps you are trying to run from fedora so I can get you the best set of bundles to duplicate this on Clear Linux?

**Comment by egernst** [comment]
while its a cool idea, I am not sure there's value-add, unless someone wants to help here.

**Comment by egernst** [comment]
WDYT @jodh-intel @bryteise @jcvenegas ?

**Comment by jodh-intel** [comment]
The clearlinux dockerfile has now been updated to Fedora 30 so this could be closed. It's a bit of a shame though as CL is the *only* rootfs image not built using itself ;(

**Comment by bryteise** [comment]
I will take a shot at the rootfs creation.

**Comment by bryteise** [comment]
@egernst Mind assigning this to me?

**Comment by jodh-intel** [comment]
@bryteise - thanks - all yours! ;)

**Comment by bryteise** [comment]
Hrm so looking at what this actually does, I'm a bit worried about the build time impact of switching to Clear Linux as it isn't trying to provide a streamlined rpm installation experience. Are there concerns about build time for these?

**Comment by devimc** [comment]
@bryteise I don't think so, our biggest concern is to include packages/binaries that potentially can increase the attack surface and bring vulnerabilities.

**Comment by jcvenegas** [comment]
@bryteise If bundle definition is not small enough today you can use an image base that uses at least rpm, in and keep the same way that the rootfs population works today ( via rpms).  At least in that way the the config can look a bit more consistent.  We did it in the past because the only bundle with rpm was os-clr-on-clr, a really big bundle for the our needs I am not sure if pundles now fix those issues.

**Comment by bryteise** [comment]
@jcvenegas We currently don't have a very size optimized rpm bundle largely due to the ecosystem using python and so it sits in the hundreds of megs. Still much smaller than the os-clr-on-clr bundle though.
